sudo: required
language: java
jdk: oraclejdk8

notifications:
  email: false

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - CODECOV_TOKEN="bad74845-3ce4-475c-8f39-f1265ffa601e"


script:
  - ./mvnw clean install -B
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
