sudo: required
language: java
jdk: oraclejdk8
 
notifications:
  email: false

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
 

script:
  - ./mvnw clean install -B
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
