sudo: required
language: java
jdk: oraclejdk8
 
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
 

 
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

